### ISSUE TITLE
Error when generating new quorra project

### ISSUE THREAD

**Issue by jmarlow4** [quorrajs/Quorra-cli#1]
I just installed the CLI and decided to give it a brief test run. I installed quorra-cli globally, everything ran smoothly, and then entered the command "quorra new quorra-blog." It says "craftng application" with a spinner for a bit then I get the familiar node error. It says this:

Command failed: quorra generate-key
module.js:442
    throw err;
Error: Cannot find module 'positron'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jason\Documents\dev\quorra-blog\bootstrap\start.js:2:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

I've tried uninstalling and reinstalling the global package twice with no avail. I am using windows. Is that a problem?

**Comment by harishanchu** [comment]
I guess its caused by the npm v3’s flat dependency structure.
